version: '3.8'
services:
  ec-service-order:
    build: ./
    image: ec-service-order:latest
    ports:
      - "8081:8081"
    environment:
      - DATABASE_SERVER=jdbc:postgresql://host.docker.internal:5432/ecsystem
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Password1
      - DATABASE_DIALECT=org.hibernate.dialect.PostgreSQL81Dialect
      - DATABASE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - INSTANCE_NAME=dev_1
      - FLYWAY_LOCATION=classpath:db/migration/postgresql
      - BATCH_JOB_FIRST_EXECUTE_ENABLE=false

